sonar.projectKey=LuSosnowski_BudgetApp-l07
sonar.organization=lusosnowski

sonar.projectName=BudgetApp-l07
sonar.projectVersion=1.0

sonar.sources=BackEnd/src/main/java,FrontEnd/src
sonar.tests=BackEnd/src/test/java

sonar.java.binaries=BackEnd/target/classes

sonar.sourceEncoding=UTF-8

sonar.exclusions=**/target/**,**/node_modules/**,**/dist/**,**/.idea/**,**/docker/**,**/*.log,**/*.zip
sonar.test.exclusions=**/target/**,**/node_modules/**,**/dist/**