sonar.projectKey=LuSosnowski_BudgetApp-l07
sonar.organization=lusosnowski

sonar.projectName=BudgetApp-l07
sonar.projectVersion=1.0

sonar.sources=backend/src/main/java,frontend/src
sonar.tests=backend/src/test/java

sonar.java.binaries=backend/target/classes

sonar.sourceEncoding=UTF-8

sonar.exclusions=**/target/**,**/node_modules/**,**/dist/**,**/.idea/**,**/docker/**,**/*.log
sonar.test.exclusions=**/target/**,**/node_modules/**,**/dist/**